kubev2v/forklift-must-gather

Dockerfile

This is an ugly hack to allow building downstream images. With the binary directly in the repository, everything is self contained, so Cachito will download the pprof binary and we will be able to use it. The downside is that putting binaries is a wrong practice, so we'll need to revert this hack. This is why I limit this change to the release-v2.0.0 branch.

Add pprof binary

---

Dockerfile

Reverts konveyor/forklift-must-gather#2.
Downstream we now have an intermediate image to build pprof, so that it can be added to the must-gather image.

Revert "Add pprof binary"

---

Dockerfile
README.md
collection-scripts/gather
collection-scripts/gather_crs
collection-scripts/targeted
collection-scripts/targeted_crs
collection-scripts/targeted_logs

In order to reduce amount of data&time must-gather takes, it was added an option to gather only given namespace, plan or VM resources.
This is related to https://github.com/konveyor/forklift-must-gather/issues/3 
Example command for targeted gathering with all possible arguments:
```
$ oc adm must-gather --image=quay.io/maufart/forklift-must-gather:targeted1 -- NS=ns1 PLAN=plan1 VM=vm-3345 /usr/bin/targeted
```
Testing image: _quay.io/maufart/forklift-must-gather:targeted1_
Demo video:
[![preview video](https://img.youtube.com/vi/c2FwJPbhnR4/0.jpg)](https://www.youtube.com/watch?v=c2FwJPbhnR4)
Possible enhancements/TODOs:
paralelize CRs gathering if needed
possible vm name/id translation

Add targeted gathering for NS, PLAN and VM

---

README.md
collection-scripts/gather_metrics

Update READE with removing not-supported metrics capture in forklift
must-gather.

Remove metrics from README

---

README.md

Backport of https://github.com/konveyor/forklift-must-gather/pull/17 - Adding information about empty files filtering of targeted must-gather
to README.
Related to https://github.com/konveyor/forklift-must-gather/pull/14 which is related to https://bugzilla.redhat.com/show_bug.cgi?id=1994978 to trigger rebuild.

[BACKPORT] Update README targeted gathering filtering

---

README.md
collection-scripts/targeted_crs

This PR finalizes must-gather changes related to Forklift 2.2 replacement of VMIO functions.
Adapting the gathering code to correctly parsing VM-related objects (VM itself and DVs). As a side-effect, VM name (instead of within-plan ID) is used be passed in parameters (as Forklift UI already does).
Fixes BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=2019307
https://bugzilla.redhat.com/show_bug.cgi?id=1995197
https://bugzilla.redhat.com/show_bug.cgi?id=2020014

Update VM parsing to use Plan instead of VMImport

---

Makefile

Adding CONTAINER_ENGINE environment variable to Makefile which is used to control if docker or podman or something else should be used for building images and running local containers.
If empty, it looks for podman by default and fallbacks to docker if /usr/bin/podman was not available.

Update Makefile allow set local container engine

---

collection-scripts/targeted_crs

A Plan CR should be enough for most of debugging purposes, however adding also Migration CR to provide really all available data in the targeted gathering archive.

Include migrations CR in targeted gathering

---

collection-scripts/targeted_logs

There was incorrect handling of VM list for virt-launcher pods logs
gathering that affected gathering of multiple VMs in list. Fixed bash
code.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1995075

Fix virt-launcher pod logs targeted gathering

---

collection-scripts/targeted_logs

2.2 backport of https://github.com/konveyor/forklift-must-gather/pull/25
There was incorrect handling of VM list for virt-launcher pods logs
gathering that affected gathering of multiple VMs in list. Fixed bash
code.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1995075

[BACKPORT] Fix virt-launcher pod logs targeted gathering

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

Adding unfiltered CDI importer logs to targeted must-gather (importer
log per-VM) and updating non-existing pod log handling.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2024506

Add Importer logs to targeted gathering

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

2.2 backport of https://github.com/konveyor/forklift-must-gather/pull/27
Adding unfiltered DCI importer logs to targeted must-gather (importer
log per-VM) and updating non-existing pod log handling.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2024506

[BACKPORT] Add Importer logs to targeted gathering

---

collection-scripts/targeted_crs

Reverts konveyor/forklift-must-gather#23
There is incorrect migration name lookup which cases problems.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2025526

Revert "Include migrations CR in targeted gathering"

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

Adding logs of virt-v2v pod which is created per-VM and has name based
on Plan name and VM ID. The log contains virt-v2v conversion info.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023680

Add virt-v2v logs to targeted gathering

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

2.2 backport of https://github.com/konveyor/forklift-must-gather/pull/32
Adding logs of virt-v2v pod which is created per-VM and has name based
on Plan name and VM ID. The log contains virt-v2v conversion info.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023680

[BACKPORT] Add virt-v2v logs to targeted gathering

---

collection-scripts/targeted_crs

Fixing typo in VirtualMachine CR parsing and storing "vmid" variable for
related log gathering e.g. virt-v2v conversion log in this case.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023680

Fix vmid in VM targeted parsing

---

collection-scripts/targeted_crs

2.2 backport of https://github.com/konveyor/forklift-must-gather/pull/34
Fixing typo in VirtualMachine CR parsing and storing "vmid" variable for
related log gathering e.g. virt-v2v conversion log in this case.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023680

[BACKPORT] Fix vmid in VM targeted parsing

---

Dockerfile

Updating oc (OpenShift client tool) to v4.9 to match to the current OpenShift version with MTV 2.2.

Upgrade oc to v4.9

---

collection-scripts/targeted_crs

A VirtualMachine CR might not exist in case of failed migration,
updating VM parsing&gathering with conditional check to not try parse
not existing VM and fail.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2027372

Handle not existing VirtualMachine

---

collection-scripts/targeted_crs

When a VM exist in a Plan, but actual VirtualMachine CR in the cluster
was deleted meanwhile, the gathering script didn't stop getting
VM-related logs which lead to messy result archive.
Adding a check if given VM really exists in the cluster.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023260

Handle missing VM resource gracefully

---

Dockerfile

Forklift must-gather image requires packages not available in RH UBIs (even in non-minimal versions), so there were
Centos 8 yum repo sources. That was recently deprecated what leads to image build failures.
Replacing Centos 8 with Centos Stream to fix upstream image build.

Fix build script with deprecated Centos 8

---

collection-scripts/targeted_crs

2.3 backport of https://github.com/konveyor/forklift-must-gather/pull/41
When a VM exist in a Plan, but actual VirtualMachine CR in the cluster
was deleted meanwhile, the gathering script didn't stop getting
VM-related logs which lead to messy result archive.
Adding a check if given VM really exists in the cluster.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023260

[BACKPORT] Handle missing VM resource gracefully

---

Dockerfile

2.3 backport of https://github.com/konveyor/forklift-must-gather/pull/42
Forklift must-gather image requires packages not available in RH UBIs (even in non-minimal versions), so there were
Centos 8 yum repo sources. That was recently deprecated what leads to image build failures.
Replacing Centos 8 with Centos Stream to fix upstream image build.

[BACKPORT] Fix build script with deprecated Centos 8

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

A VM migration can include pre and post migration hooks which are Jobs (k8s resources) that could contain relevant information in their log files. Adding migration hooks jobs logs to the targeted gathering.
Addresses https://github.com/konveyor/forklift-must-gather/issues/45 and fixes https://bugzilla.redhat.com/show_bug.cgi?id=2059335

Gather migration hooks logs

---

collection-scripts/targeted_logs

Virtv2v pods are named based on the plan name and VM id. If the plan and VM id are too long, the name of the pod will be truncated and not contain the entire plan or VM id. Targeted log collection will fail for such a pod, as the collection script attempts to grep for the entire VM id in the pod name.
Because the collection script already filters for pods based on the vmID label, this additional grep for the VM id in the pod name should be redundant. Removing it allows the pod to be found and logs collected.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2064336

Bug 2064336: Fix log collection of virtv2v pods with long names

---

collection-scripts/targeted_crs

Targeted collection fails for a VM if its name is a substring of another VM in the same namespace, due to grep returning multiple matches for the name. Add -w flag to do a whole-word comparison and avoid the collision.
```
sh-4.4$ oc get virtualmachines -A | grep auto-rhv-red-iscsi-migration-50gb-70usage-vm-2
openshift-mtv   auto-rhv-red-iscsi-migration-50gb-70usage-vm-2    5d12h   Stopped   False
openshift-mtv   auto-rhv-red-iscsi-migration-50gb-70usage-vm-20   5d11h   Stopped   False
openshift-mtv   auto-rhv-red-iscsi-migration-50gb-70usage-vm-21   5d11h   Stopped   False
openshift-mtv   auto-rhv-red-iscsi-migration-50gb-70usage-vm-22   5d11h   Stopped   False
openshift-mtv   auto-rhv-red-iscsi-migration-50gb-70usage-vm-23   5d11h   Stopped   False
openshift-mtv …
```

Fix collision when collecting VM CRs

---

collection-scripts/targeted_crs

Targeted collection fails for a VM if its name is a substring of another VM in the same namespace, due to grep returning multiple matches for the name. Add -w flag to do a whole-word comparison and avoid the collision.

Backport #54 to v2.3.2

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

Since we moved to post the VM in the last phase, the VM now usually
contains PVC in the volume spec instead of DV. We need to look on both
in order to gather the relevant data.
Also, adding migrations IDs based on the VM label. This will allow us to
gather the populator pod logs when there is no plan ID provided.

Fix the gathering of importer and populator pods logs

---

collection-scripts/targeted_crs
collection-scripts/targeted_logs

When importing using CDI in warm migrations we may have multiple PVCs (scratch) and multiple importer pods to the migration. This patch adds the logs of these relevant resources.

Add warm migration resources

---

collection-scripts/targeted_crs

Gather the PVCs from populator flow, including the prime PVC if exists.

Gather all populator PVCs

---

Dockerfile

We no longer need the graphviz, removing from deps.

KFLUXMIG-86 | Remove graphviz from Dockerfile deps

---

.gitignore
.tekton/forklift-must-gather-pull-request.yaml
.tekton/forklift-must-gather-push.yaml
Dockerfile-downstream
redhat.repo
rpms.in.yaml
rpms.lock.yaml

This enables hermetic builds of forklift-must-gather image in Konflux.
Changes:
- Add downstream containerfiles
- Enable hermetic builds in build pipelines
- Add rpms.in.yaml, rpms.lock.yaml and redhat.repo files

Enable hermetic build for forklift-must-gather

---

build/Dockerfile-downstream

Add missing args instructions into dockerfile for konflux build-args-file.

Add missing args

---

collection-scripts/gather_logs

Right now, we collect v2v logs only when users specify the customers specify the  VM variable. Most often, the customer does not specify any VM name, so we do not end up collecting the v2v logs. We should collect all the v2v by default
Ref: https://issues.redhat.com/browse/MTV-2980

MTV-2980 | Include all v2v logs in MTV must gather

---

build/Dockerfile-downstream

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for forklift-must-gather-dev-preview

---

build/Dockerfile-downstream

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for forklift-must-gather-2-8
